In [ ]:
##numpy -- numerical python 
##mathematical and scientific computing library
##array -- collection of similar type of data

##list vs array 

# array --1d , 2d ,3d 
#1d -- list 
##2d array - matrices - row and columns  --m x n --shape 
## 3d array == 2d array ki array 
#pip install numpy

In [1]:
import numpy as np

In [20]:
##array creation 
arr1 = np.array([0,0,1,1,0,0])
ar1=arr1.reshape(2,3)
ar1

array([[0, 0, 1],
       [1, 0, 0]])

In [5]:
arr2 = np.arange(1,6)
arr2

array([1, 2, 3, 4, 5])

In [6]:
arr3 = np.zeros(5)
arr3

array([0., 0., 0., 0., 0.])

In [16]:
arr4 = np.ones((2,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
arr5 = np.linspace(1,10,200)
arr5

array([ 1.        ,  1.04522613,  1.09045226,  1.13567839,  1.18090452,
        1.22613065,  1.27135678,  1.31658291,  1.36180905,  1.40703518,
        1.45226131,  1.49748744,  1.54271357,  1.5879397 ,  1.63316583,
        1.67839196,  1.72361809,  1.76884422,  1.81407035,  1.85929648,
        1.90452261,  1.94974874,  1.99497487,  2.04020101,  2.08542714,
        2.13065327,  2.1758794 ,  2.22110553,  2.26633166,  2.31155779,
        2.35678392,  2.40201005,  2.44723618,  2.49246231,  2.53768844,
        2.58291457,  2.6281407 ,  2.67336683,  2.71859296,  2.7638191 ,
        2.80904523,  2.85427136,  2.89949749,  2.94472362,  2.98994975,
        3.03517588,  3.08040201,  3.12562814,  3.17085427,  3.2160804 ,
        3.26130653,  3.30653266,  3.35175879,  3.39698492,  3.44221106,
        3.48743719,  3.53266332,  3.57788945,  3.62311558,  3.66834171,
        3.71356784,  3.75879397,  3.8040201 ,  3.84924623,  3.89447236,
        3.93969849,  3.98492462,  4.03015075,  4.07537688,  4.12

In [15]:
arr6 = np.arange(60).reshape(6,10)
arr6

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [32]:
# print(arr6.shape)      ##rows and columns
# arr6.dtype
# arr6.size
# arr6.ndim

# print(arr6.T.shape)
arr6.flatten()
arr6.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [30]:
##random numbers 
# arr7 = np.random.random(10)
arr7 = np.random.randint(1,10,100)
arr7


array([4, 4, 4, 9, 9, 6, 3, 5, 1, 5, 2, 5, 7, 1, 9, 1, 2, 8, 8, 6, 4, 6,
       1, 9, 2, 9, 2, 7, 7, 3, 6, 4, 9, 1, 4, 6, 2, 9, 9, 4, 9, 9, 2, 3,
       9, 5, 2, 7, 2, 4, 2, 2, 3, 9, 8, 8, 9, 8, 1, 5, 9, 3, 9, 3, 9, 5,
       3, 4, 8, 3, 8, 7, 6, 1, 8, 9, 8, 1, 4, 5, 7, 7, 1, 7, 2, 3, 3, 5,
       4, 4, 2, 9, 4, 6, 7, 9, 6, 1, 9, 6])

In [33]:
arr8 = np.random.randint(1,10,(3,4))
arr8

array([[5, 9, 8, 5],
       [4, 3, 1, 5],
       [8, 9, 1, 9]])

In [34]:
arr9 = np.arange(225).reshape(3,15,5)
arr9

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99],
        [100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124],
        [125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134],
        [135, 136, 137, 138, 139],
        [140, 141,

In [ ]:
np.max(arr9)
np.min(arr9)
np.mean(arr9)
np.median(arr9)
np.std(arr9)


64.95126378036586

In [39]:
for i in range(19,191,19):
    print(i)

19
38
57
76
95
114
133
152
171
190
